service: api
app: intercity

provider:
  name: aws
  runtime: nodejs14.x

functions:
  intercity:
    architecture: arm64
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
